### ISSUE TITLE
Residual function implementations repeatedly query mjModel for sensors by name

### ISSUE THREAD

**Issue by nimrod-gileadi** [deepmind/mujoco_mpc#1]
Residual function implementations like mjpc::Humanoid::ResidualStand use SensorByName on every call, to find relevant sensors in the model.

This function involves a linear search over sensors names, and shouldn't be run on every step of every rollout.
One solution would be to turn the residual from a pure function to an object which gets initialized once with the model, and caches those lookups.

**Comment by erez-tom** [comment]
This also affects Trajectory::Rollout, which looks for the sensor "trace".

**Comment by yuvaltassa** [comment]
I don't think this is a real problem. The search is very fast and the code is simpler this way. IMO

**Comment by yuvaltassa** [comment]
Solved by recent improvements to `mj_name2id`
