### ISSUE TITLE
Tutorial or Document Needed!

### ISSUE THREAD

**Issue by SiyuanHuang95** [deepmind/mujoco_mpc#138]
Hi,

thanks for your contribution and open-sourcing! I have watched some demo videos from yours and quite impressive!

I am with the background of SLAM / 3D point cloud perception, and would like to have some trials for the combination of dynamics like MJPC with other stuff. However, I found that there is almost no docs for this project,

Can you provide any docs or information wrt the usage. Basically, I am trying to control a quadruped's pose with python API and it's pose could be online solved with MJPC. This task is similar with your demo [HERE](https://www.youtube.com/watch?v=esLuwaWz4oE) but with python API.

Bests

**Comment by thowell** [comment]
Documentation is available [here](https://github.com/deepmind/mujoco_mpc/tree/main/docs).

**Comment by SiyuanHuang95** [comment]
Thanks for your quick reply.

The link you shared is more about the GUI introduction, would there be any possibility for the Python API Doc or some demo codes?
