### ISSUE TITLE
"grey_grid" material uses "blue_grid" texture

### ISSUE THREAD

**Issue by lieskjur** [deepmind/mujoco_mpc#147]
Hi, I found the smallest of mistakes in [common.xml](https://github.com/deepmind/mujoco_mpc/blob/760202e9e411f2dda1038e85b2277788fbfaa9ac/mjpc/tasks/common.xml) at line 15 where the "grey_grid" material is defined using the wrong texture.

**Comment by thowell** [comment]
Good catch! Fixed in #148.
