### ISSUE TITLE
Compile error in Simulate.cc: error: no member named 'nstack' in 'mjData_

### ISSUE THREAD

**Issue by nkhosh** [deepmind/mujoco_mpc#168]
Probably related to commit daa2ac7 on mujoco. I have this error when recompiling.

`simulate.cc:493:52: error: no member named 'nstack' in 'mjData_'; did you mean 'pstack'?
[build]                      d->maxuse_arena / (double)(d->nstack * sizeof(mjtNum)),`

**Comment by saran-t** [comment]
Someone needs to merge the `deepmind` branch to `main`.

**Comment by saran-t** [comment]
(In the meantime you should be able to build against the `deepmind` branch)

**Comment by nkhosh** [comment]
Thanks for the quick response!
I'm working on a clone of the mujoco_mpc repo, in a local branch, which is not up to date with the latest commits of the origin. The issue is that when I rebuild, it fetches the latest version from the main branch for the dependencies. Ideally, my work shouldn't be affected by the latest changes unless I explicitly fetch and merge the code.
Is there any workaround I could use to solve the build issue without needing to merge with the latest version of the deepmind branch? This would be helpful for similar issues in the future as well.

**Comment by saran-t** [comment]
Yes, change [this line](https://github.com/deepmind/mujoco_mpc/blob/main/CMakeLists.txt#L68) to the commit hash that you want to pin.
