### ISSUE TITLE
Rewrite FindInterval

### ISSUE THREAD

**Issue by yuvaltassa** [deepmind/mujoco_mpc#19]
The function [FindInterval](https://github.com/deepmind/mujoco_mpc/blob/3573be285565ddf585c655b995f606c891c93569/mjpc/utilities.cc#L120) should be rewritten using [std::lower_bound](https://en.cppreference.com/w/cpp/algorithm/lower_bound). There is no reason to write our own binary search function.

**Comment by thowell** [comment]
#74

**Comment by thowell** [comment]
#75
