### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by ahip88** [deepmind/mujoco_mpc#39]
Currently my robot's motor control and RL loop are hooked up in Python. If I wish to use MPC in the pipeline, the alternative is to rewrite what I have in C++. Are python bindings by any chance in the roadmap?

**Comment by thowell** [comment]
Yes. This is something we will do early 2023.

**Comment by adeeb10abbas** [comment]
@thowell if you don't mind, could you please create a meta issue to track smaller issues regarding the Python bindings? It'd be very useful and I would be very much interested in contributing if there was a set path. Thanks! Great work btw.
