### ISSUE TITLE
Add documentation for required libraries

### ISSUE THREAD

**Issue by dtch1997** [deepmind/mujoco_mpc#42]
For new users setting up for the first time, it may be helpful to include documentation on certain libraries that need to be installed. On Ubuntu 20.04, I had to install the following additional libraries before CMake would run successfully: 
```
$ history | grep "sudo apt install"
sudo apt install libxrandr-dev
sudo apt install libxinerama-dev
sudo apt install libxcursor-dev
sudo apt install libxi-dev
```

**Comment by thowell** [comment]
Thanks! I have experienced this issue on Ubuntu as well.

The README is updated in this PR #44
