### ISSUE TITLE
Improved iLQG nominal rollout

### ISSUE THREAD

**Issue by yuvaltassa** [deepmind/mujoco_mpc#57]
The iLQG nominal rollout, defined [here](https://github.com/deepmind/mujoco_mpc/blob/15b4385b6e7a662d4f37ada404aead2b16e0c3ce/mjpc/planners/ilqg/planner.cc#L344), is inefficient. We should do this with a threadpool that rolls out with a parallel "line search" **on the feedback term**, that includes a 0 coefficient (no feedback, just open-loop). For this, the [`Action`](https://github.com/deepmind/mujoco_mpc/blob/15b4385b6e7a662d4f37ada404aead2b16e0c3ce/mjpc/planners/ilqg/policy.cc#L80) method should also get a `feedback_scale` parameter (defaulting to 1), and [this line](https://github.com/deepmind/mujoco_mpc/blob/15b4385b6e7a662d4f37ada404aead2b16e0c3ce/mjpc/planners/ilqg/policy.cc#L148) should use `mju_addToScl`.

This is a very simple change that I suspect will improve iLQG significantly.

**Comment by thowell** [comment]
Implemented in #62
